#!/bin/sh

PATH_ELEMS="$(echo ${PATH} | tr -s ':' '\n')"

ORIG_GHCI_BINARY=""

for PATH_ELEM in ${PATH_ELEMS}; do
    GHCI_CANDIDATE="${PATH_ELEM}/ghci"
    if command -v "${GHCI_CANDIDATE}" > /dev/null 2> /dev/null; then
        if [ "${0}" != "${GHCI_CANDIDATE}" ]; then
            if [ -z "${GHCI_PKG_BINARY}" ]; then
                ORIG_GHCI_BINARY="${GHCI_CANDIDATE}"
            fi
        fi
    fi
done

if [ -z "${ORIG_GHCI_BINARY}" ]; then
    echo "ghci wrapper: Couldn't find real ghc-pkg program"
    exit 1
fi


GHCI_PACKAGE_DB_LIST="$(cat <HSENV_DIR>/ghc_package_path_var)"
GHCI_PACKAGE_DB="-package-db "`echo ${GHCI_PACKAGE_DB_LIST} | sed 's/ / -package-db /g'`


exec "${ORIG_GHCI_BINARY}" ${GHCI_PACKAGE_DB} "${@}"

